/**:
  ros__parameters:
    video_device: "/dev/video2" # check device number by VLC player or `v4l2-ctl --list-device`
    framerate: 10.0 # use `v4l2-ctl --device /dev/video2 --list-formats-ex` to check format and framerate
    io_method: "mmap"
    frame_id: "arena"
    pixel_format: "mjpeg2rgb"
    image_width: 800
    image_height: 600
    camera_name: "arena_cam"
    power_line_frequency: 2
